### ISSUE TITLE
Test Chamber Alignment

### ISSUE THREAD

**Issue by aadvaark** [akvo/akvo-caddisfly-colorimetry-hardware#2]
The 'mesh', or the target the camera focuses on is very small. Any slight misalignment can cause results to be off.

**Comment by saurabhlevin** [comment]
This has been (somewhat) addressed with the new twist-&-lock design, and Nischal's update 0.48.
The new design requires fewer rotations (and hence more predictable alignment), and has an increased footprint to fit the flashes on most cameras. Nischal's update allows us to center the mesh directly over the camera lens quite easily.
Issues:
The cartridge is still quite complicated to assemble, and requires even more parts for manufacturing.

Twist &lock Cartridge:

![img_20150319_124917477](https://cloud.githubusercontent.com/assets/8445292/6728448/e7a13150-ce4f-11e4-9c69-904bf9c2cbb1.jpg)

![dsc_0026](https://cloud.githubusercontent.com/assets/8445292/6728441/da764858-ce4f-11e4-8d5a-385a3d0015cb.JPG)
![dsc_0027](https://cloud.githubusercontent.com/assets/8445292/6728442/da77f338-ce4f-11e4-9759-82ca03633018.JPG)

**Comment by aadvaark** [comment]
Looks fairly stable for now.
